/*
MIT License
Copyright (c) 2024 - 2026 René Amthor (tobid7)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
 */

#include <lazyvec.hpp>

constexpr std::string_view _template = R"text(#pragma once

/*
MIT License
Copyright (c) 2024 - 2026 René Amthor (tobid7)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
 */

// This file is generated by lazyvec 2.0.0

#include <pd/core/common.hpp>
{7}

namespace PD {{
template <typename T>
class vec{0} {{
public:
{1}
  // Constructors
{2}
  // Operations
{3}
  // Generic Operations
{4}
  // Functions
{5}
  // Swap Functions
{6}
}};
using fvec{0} = vec{0}<float>;
using ivec{0} = vec{0}<int>;
using dvec{0} = vec{0}<double>;
}}  // namespace PD
)text";

namespace LVec {
std::string GenerateHeader(int n) {
  std::stringstream ops, data, extended;
  for (int i = 0; i < n; i++) {
    data << "T " << elems[i] << ";" << std::endl;
  }
  ops << MakeOperationFor('+', n);
  ops << MakeOperationFor('-', n);
  ops << MakeOperationFor('*', n);
  ops << MakeOperationFor('/', n);
  if (n > 2) {
    extended << "// Extended includes (rename if you use other filenames/paths)"
             << std::endl;
    extended << "#include <vec2.hpp>" << std::endl;
    if (n == 4) {
      extended << "#include <vec3.hpp>" << std::endl;
    }
  }
  return std::format(_template, n, data.str(), MakeConstructors(n), ops.str(),
                     GenericOperations(n), MakeFunctions(n), MakeSwap(n),
                     extended.str());
}
}  // namespace LVec